### ISSUE TITLE
Unhandled Exception: org.bluez.Error.InProgress: Operation already in progress

### ISSUE THREAD

**Issue by Finnomator** [Cupcake-Systems/path_pilot#17]
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: org.bluez.Error.InProgress: Operation already in progress
#0      _BlueZObject.callMethod (package:bluez/src/bluez_client.dart:1022:11)
<asynchronous suspension>
#1      BlueZAdapter.startDiscovery (package:bluez/src/bluez_client.dart:229:5)
<asynchronous suspension>
#2      UniversalBleLinux.startScan (package:universal_ble/src/universal_ble_linux/universal_ble_linux.dart:83:5)
<asynchronous suspension>
#3      _QueuedFuture.execute (package:universal_ble/src/queue.dart:67:18)
<asynchronous suspension>
```

**Comment by Finnomator** [comment]
Bluetooth is currently not supported.
